"""Default corpus registry for clio — primary historical source texts."""
CLIO_DEFAULT_CORPUSES = [
    {"id": "gutenberg-herodotus",    "name": "The Histories (Herodotus)",
     "source_type": "gutenberg",     "source": "2707",
     "topics": ["ancient", "greece", "persia", "war"],
     "description": "Herodotus — father of history, Persian Wars"},
    {"id": "gutenberg-thucydides",   "name": "History of the Peloponnesian War",
     "source_type": "gutenberg",     "source": "7142",
     "topics": ["ancient", "greece", "war", "politics"],
     "description": "Thucydides — the Peloponnesian War"},
    {"id": "gutenberg-plutarch",     "name": "Parallel Lives (Plutarch)",
     "source_type": "gutenberg",     "source": "674",
     "topics": ["ancient", "biography", "rome", "greece"],
     "description": "Plutarch — Lives of famous Greeks and Romans"},
    {"id": "gutenberg-caesar",       "name": "The Gallic Wars (Caesar)",
     "source_type": "gutenberg",     "source": "10657",
     "topics": ["roman", "war", "gaul", "caesar"],
     "description": "Julius Caesar's first-hand account of the Gallic Wars"},
    {"id": "gutenberg-tacitus",      "name": "The Annals (Tacitus)",
     "source_type": "gutenberg",     "source": "10902",
     "topics": ["roman", "empire", "politics"],
     "description": "Tacitus — the early Roman Empire"},
    {"id": "gutenberg-livy",         "name": "History of Rome (Livy)",
     "source_type": "gutenberg",     "source": "19725",
     "topics": ["roman", "republic", "founding"],
     "description": "Livy — Ab Urbe Condita, from the founding of Rome"},
    {"id": "gutenberg-art-of-war",   "name": "The Art of War (Sun Tzu)",
     "source_type": "gutenberg",     "source": "17405",
     "topics": ["chinese", "military", "strategy", "ancient"],
     "description": "Sun Tzu's military treatise"},
    {"id": "gutenberg-machiavelli",  "name": "The Prince (Machiavelli)",
     "source_type": "gutenberg",     "source": "1232",
     "topics": ["renaissance", "politics", "italy"],
     "description": "Machiavelli's political treatise"},
    {"id": "gutenberg-gibbon",       "name": "Decline and Fall of the Roman Empire (Gibbon)",
     "source_type": "gutenberg",     "source": "731",
     "topics": ["roman", "empire", "medieval", "decline"],
     "description": "Gibbon's monumental history of Rome"},
    {"id": "gutenberg-marco-polo",   "name": "The Travels of Marco Polo",
     "source_type": "gutenberg",     "source": "10636",
     "topics": ["medieval", "exploration", "asia", "mongol"],
     "description": "Marco Polo's account of his travels to Asia"},
    {"id": "gutenberg-federalist",   "name": "The Federalist Papers",
     "source_type": "gutenberg",     "source": "1404",
     "topics": ["american", "politics", "founding", "constitution"],
     "description": "Hamilton, Madison, Jay — arguments for the US Constitution"},
    {"id": "gutenberg-common-sense", "name": "Common Sense (Thomas Paine)",
     "source_type": "gutenberg",     "source": "147",
     "topics": ["american", "revolution", "politics"],
     "description": "Paine's argument for American independence"},
    {"id": "gutenberg-darwin",       "name": "On the Origin of Species (Darwin)",
     "source_type": "gutenberg",     "source": "1228",
     "topics": ["science", "biology", "evolution", "victorian"],
     "description": "Darwin's theory of evolution by natural selection"},
    {"id": "gutenberg-adam-smith",   "name": "The Wealth of Nations (Adam Smith)",
     "source_type": "gutenberg",     "source": "3300",
     "topics": ["economics", "enlightenment", "capitalism"],
     "description": "Adam Smith — foundations of modern economics"},
]
